// src/components/Inventory/AddEditProductForm.jsx
import React, { useState, useRef, useEffect } from 'react';
import { Plus, Upload, Loader2, Save, Settings, Package, DollarSign, AlertTriangle, X, Trash2, XCircle } from 'lucide-react';
import { useTheme } from '../../context/ThemeContext';
import VariantForm from './VariantForm';
import ErrorBoundary from '../Common/ErrorBoundary';

const AddEditProductForm = ({
    isOpen,
    onClose,
    title,
    isNewProduct,
    productData,
    formErrors,
    imagePreviewUrl,
    isUploadingMainImage,
    loading,
    onSubmit,
    handleProductInputChange,
    handleAddVariant,
    handleRemoveVariant,
    handleVariantInputChange,
    handleMainImageFileChange,
    handleVariantImageFileChange,
    variantImageUploading,
    unitOfMeasureOptions,
    availableCurrencies,
    calculatedProductProfitPercentage,
    calculatedProductPricePlaceholder,
    calculatedVariantProfitPercentage,
    calculatedVariantPricePlaceholder,
    formatPrice,
    autoGeneratedSku,
    isMainSkuManuallyEdited,
    handleMainImageUrlBlur,
    globalProductSuggestions,
    showGlobalSuggestions,
    handleSelectGlobalProduct,
    handleRemoveMainImage,
}) => {
    if (!isOpen) return null;
    
    const { theme } = useTheme();
    const [currentPage, setCurrentPage] = useState(0);
    const [expandedVariants, setExpandedVariants] = useState(new Set());
    const [showVariantDeleteConfirm, setShowVariantDeleteConfirm] = useState(false);
    const sectionRefs = useRef({});
    
    // Definir las páginas del formulario
    const getPages = () => {
        const basePages = [
            { id: 'basic', title: 'Información Básica', icon: '📝', color: 'blue' },
            { id: 'pricing', title: 'Costos y Precios', icon: '💰', color: 'green' },
            { id: 'advanced', title: 'Opciones Avanzadas', icon: '⚙️', color: 'orange' }
        ];
        
        if (productData.variants && productData.variants.length > 0) {
            basePages.push({ id: 'variants', title: 'Variantes', icon: '🎨', color: 'purple' });
            productData.variants.forEach((variant, index) => {
                basePages.push({
                    id: `variant-${index}`,
                    title: variant.name || `Variante ${index + 1}`,
                    icon: '🎯',
                    color: 'purple',
                    isVariant: true
                });
            });
        }
        
        return basePages;
    };
    
    const pages = getPages();
    const totalPages = pages.length;
    const activeSection = pages[currentPage]?.id || 'basic';
    
    const currencies = availableCurrencies && availableCurrencies.length > 0 
        ? availableCurrencies 
        : ['USD', 'VES', 'EUR'];

    const goToPage = (pageIndex) => {
        if (pageIndex >= 0 && pageIndex < totalPages) {
            setCurrentPage(pageIndex);
        }
    };
    
    const nextPage = () => {
        if (currentPage < totalPages - 1) {
            setCurrentPage(currentPage + 1);
        }
    };
    
    const prevPage = () => {
        if (currentPage > 0) {
            setCurrentPage(currentPage - 1);
        }
    };
    
    const scrollToSection = (sectionId) => {
        const pageIndex = pages.findIndex(page => page.id === sectionId);
        if (pageIndex !== -1) {
            goToPage(pageIndex);
        }
    };

    // Atajos de teclado para navegación
    useEffect(() => {
        const handleKeyDown = (event) => {
            if (event.key === 'ArrowLeft' && !event.target.matches('input, textarea, select')) {
                event.preventDefault();
                prevPage();
            } else if (event.key === 'ArrowRight' && !event.target.matches('input, textarea, select')) {
                event.preventDefault();
                nextPage();
            }
        };
        
        if (isOpen) {
            document.addEventListener('keydown', handleKeyDown);
        }
        
        return () => {
            document.removeEventListener('keydown', handleKeyDown);
        };
    }, [isOpen, currentPage, totalPages]);

    const toggleVariantExpansion = (variantIndex) => {
        setExpandedVariants(prev => {
            const newSet = new Set(prev);
            if (newSet.has(variantIndex)) {
                newSet.delete(variantIndex);
            } else {
                newSet.add(variantIndex);
            }
            return newSet;
        });
        setTimeout(() => scrollToSection(`variant-${variantIndex}`), 100);
    };

    const getVariantStatus = (variant, index) => {
        const hasErrors = Object.keys(formErrors).some(key => key.startsWith(`variant-${index}-`));
        const isComplete = variant.name && variant.costPrice && variant.stock;
        
        if (hasErrors) return '⚠️';
        if (isComplete) return '✅';
        return index + 1;
    };

    const getSectionStatus = (sectionName) => {
        const sectionErrors = {
            basic: ['name', 'category'].some(field => formErrors[field]),
            pricing: ['costPrice', 'stock', 'unitOfMeasure'].some(field => formErrors[field]),
            variants: productData.variants?.some((_, index) => 
                Object.keys(formErrors).some(key => key.startsWith(`variant-${index}-`))
            ),
            advanced: ['reorderThreshold', 'optimalMaxStock', 'shelfLifeDays'].some(field => formErrors[field])
        };
        return sectionErrors[sectionName] ? '⚠️' : null;
    };

    const getFormProgress = () => {
        const totalFields = ['name', 'category', 'costPrice', 'stock'];
        const completedFields = totalFields.filter(field => productData[field]);
        return Math.round((completedFields.length / totalFields.length) * 100);
    };

    const hasVariantContent = () => {
        return productData.variants?.some(variant => 
            variant.name || variant.costPrice || variant.stock || variant.sku || 
            variant.color || variant.size || variant.material || variant.imageUrl
        );
    };

    const handleProductTypeChange = (hasVariants) => {
        if (!hasVariants && productData.variants?.length > 0 && hasVariantContent()) {
            setShowVariantDeleteConfirm(true);
        } else {
            handleProductInputChange({ target: { name: 'variants', value: hasVariants ? [{}] : [] } });
        }
    };

    const confirmDeleteVariants = () => {
        handleProductInputChange({ target: { name: 'variants', value: [] } });
        setShowVariantDeleteConfirm(false);
    };

    useEffect(() => {
        const handleEscape = (event) => {
            if (event.key === 'Escape') {
                onClose();
            }
        };
        
        const handleClickOutside = (event) => {
            if (showGlobalSuggestions && !event.target.closest('.suggestions-dropdown')) {
                // Cerrar sugerencias si se hace clic fuera
            }
        };
        
        if (isOpen) {
            document.addEventListener('keydown', handleEscape);
            document.addEventListener('mousedown', handleClickOutside);
        }
        
        return () => {
            document.removeEventListener('keydown', handleEscape);
            document.removeEventListener('mousedown', handleClickOutside);
        };
    }, [isOpen, onClose, showGlobalSuggestions]);
    
    // Resetear página al abrir modal
    useEffect(() => {
        if (isOpen) {
            setCurrentPage(0);
        }
    }, [isOpen]);

    return (
        <div
            className="fixed inset-0 bg-black/80 backdrop-blur-sm flex items-center justify-center z-50 transition-all duration-300 p-4 sm:p-6 overflow-y-auto animate-in fade-in-0"
            onClick={onClose}
        >
            <div
                className="bg-deep-night-blue/95 backdrop-blur-xl rounded-2xl shadow-2xl border border-white/10 text-neutral-light w-full max-w-2xl lg:max-w-4xl xl:max-w-5xl mx-auto my-auto relative transform transition-all duration-500 scale-100 flex flex-col max-h-[90vh] overflow-hidden animate-in zoom-in-95 slide-in-from-bottom-4"
                onClick={(e) => e.stopPropagation()}
            >
                <div className="relative bg-gradient-to-r from-gray-800 to-gray-700">
                    <div className="p-4 ml-56">
                        <button
                            onClick={onClose}
                            className="absolute top-3 right-3 text-neutral-gray-400 hover:text-red-500 transition-colors duration-200 z-10"
                            title="Cerrar"
                        >
                            <XCircle size={28} />
                        </button>
                        <h3 className="text-2xl sm:text-3xl font-bold text-copper-rose-accent text-center pr-12">
                            {title}
                        </h3>
                    </div>
                </div>
                <div className="overflow-y-auto flex-grow">
                    <ErrorBoundary>
                        <div className={`flex h-[70vh] relative ${
                            theme === 'light' ? 'bg-surface-primary' : 'bg-gradient-to-br from-gray-900 to-gray-800'
                        }`}>
                            {/* Sidebar */}
                            <div className={`w-56 flex-shrink-0 p-3 border-r border-opacity-30 overflow-y-auto backdrop-blur-sm ${
                                theme === 'light' ? 'border-border-subtle bg-surface-secondary/80' : 'border-gray-600 bg-gray-800/90'
                            }`} style={{
                                scrollbarWidth: 'thin',
                                scrollbarColor: '#9ca3af #374151'
                            }}>
                                {/* Imagen del producto */}
                                <div className={`w-full h-32 rounded-2xl overflow-hidden mb-3 relative shadow-lg ring-1 ring-white/10 ${
                                    theme === 'light' ? 'bg-gradient-to-br from-gray-100 to-gray-200' : 'bg-gradient-to-br from-gray-700 to-gray-600'
                                }`}>
                                    {(imagePreviewUrl || productData.imageUrl) && !isUploadingMainImage ? (
                                        <>
                                            <img
                                                src={imagePreviewUrl || productData.imageUrl}
                                                alt="Producto"
                                                className="w-full h-full object-cover"
                                                onError={(e) => {
                                                    e.target.style.display = 'none';
                                                    e.target.nextSibling.style.display = 'flex';
                                                }}
                                            />
                                            <div className={`w-full h-full items-center justify-center text-4xl font-bold hidden ${
                                                theme === 'light' 
                                                    ? 'bg-gradient-to-br from-red-400 to-orange-500 text-white' 
                                                    : 'bg-gradient-to-br from-red-500 to-orange-600 text-white'
                                            }`}>
                                                ❌
                                            </div>
                                            {/* Botón eliminar imagen */}
                                            <button
                                                type="button"
                                                onClick={handleRemoveMainImage}
                                                className="absolute top-1 right-1 w-6 h-6 bg-red-500 hover:bg-red-600 text-white rounded-full flex items-center justify-center text-xs font-bold transition-colors shadow-lg"
                                                title="Eliminar imagen"
                                            >
                                                ×
                                            </button>
                                        </>
                                    ) : (
                                        <div className={`w-full h-full flex items-center justify-center text-4xl font-bold ${
                                            theme === 'light' 
                                                ? 'bg-gradient-to-br from-blue-400 to-purple-500 text-white' 
                                                : 'bg-gradient-to-br from-blue-500 to-purple-600 text-white'
                                        }`}>
                                            {productData.name ? productData.name.charAt(0).toUpperCase() : 'P'}
                                        </div>
                                    )}
                                    {isUploadingMainImage && (
                                        <div className="absolute inset-0 bg-black bg-opacity-50 flex items-center justify-center">
                                            <Loader2 size={24} className="animate-spin text-white" />
                                        </div>
                                    )}
                                </div>

                                {/* Botón subir imagen */}
                                <div className="mb-4">
                                    <label htmlFor="main-image-upload" className={`w-full py-2 px-3 rounded-xl text-center cursor-pointer transition-all duration-200 text-xs flex items-center justify-center gap-1.5 font-medium shadow-lg hover:shadow-xl hover:scale-105 ${
                                        theme === 'light' 
                                            ? 'bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white' 
                                            : 'bg-gradient-to-r from-blue-500 to-blue-600 hover:from-blue-600 hover:to-blue-700 text-white'
                                    }`}>
                                        {isUploadingMainImage ? <Loader2 size={14} className="animate-spin" /> : <Upload size={14} />}
                                        Subir
                                    </label>
                                    <input
                                        id="main-image-upload"
                                        type="file"
                                        accept="image/jpeg,image/jpg,image/png,image/gif,image/webp"
                                        onChange={handleMainImageFileChange}
                                        className="hidden"
                                    />
                                </div>

                                {/* Índice de navegación */}
                                <div className={`rounded-xl p-3 backdrop-blur-sm shadow-inner ring-1 ring-white/5 ${
                                    theme === 'light' ? 'bg-surface-primary/80' : 'bg-gray-700/80'
                                }`}>
                                    <div className="flex items-center justify-between mb-2">
                                        <h4 className={`text-xs font-bold ${
                                            theme === 'light' ? 'text-text-emphasis' : 'text-gray-100'
                                        }`}>PÁGINAS</h4>
                                        <div className={`text-xs px-2 py-1 rounded-full font-semibold shadow-sm ring-1 ring-white/10 ${
                                            theme === 'light' ? 'bg-gradient-to-r from-blue-100 to-blue-200 text-blue-800' : 'bg-gradient-to-r from-blue-900/60 to-blue-800/60 text-blue-200'
                                        }`}>
                                            {currentPage + 1} / {totalPages}
                                        </div>
                                    </div>
                                    
                                    <div className="space-y-1">
                                        {pages.map((page, index) => {
                                            const isActive = currentPage === index;
                                            const colorClasses = {
                                                blue: isActive 
                                                    ? theme === 'light' ? 'bg-blue-100 text-blue-800 shadow-sm ring-1 ring-blue-200' : 'bg-blue-900/60 text-blue-200 shadow-sm ring-1 ring-blue-700/50'
                                                    : theme === 'light' ? 'hover:bg-blue-50 text-text-base hover:shadow-sm' : 'hover:bg-blue-900/20 text-gray-300 hover:shadow-sm',
                                                green: isActive 
                                                    ? theme === 'light' ? 'bg-green-100 text-green-800 shadow-sm ring-1 ring-green-200' : 'bg-green-900/60 text-green-200 shadow-sm ring-1 ring-green-700/50'
                                                    : theme === 'light' ? 'hover:bg-green-50 text-text-base hover:shadow-sm' : 'hover:bg-green-900/20 text-gray-300 hover:shadow-sm',
                                                orange: isActive 
                                                    ? theme === 'light' ? 'bg-orange-100 text-orange-800 shadow-sm ring-1 ring-orange-200' : 'bg-orange-900/60 text-orange-200 shadow-sm ring-1 ring-orange-700/50'
                                                    : theme === 'light' ? 'hover:bg-orange-50 text-text-base hover:shadow-sm' : 'hover:bg-orange-900/20 text-gray-300 hover:shadow-sm',
                                                purple: isActive 
                                                    ? theme === 'light' ? 'bg-purple-100 text-purple-800 shadow-sm ring-1 ring-purple-200' : 'bg-purple-900/60 text-purple-200 shadow-sm ring-1 ring-purple-700/50'
                                                    : theme === 'light' ? 'hover:bg-purple-50 text-text-base hover:shadow-sm' : 'hover:bg-purple-900/20 text-gray-300 hover:shadow-sm'
                                            };
                                            
                                            return (
                                                <div key={page.id} className={`flex items-center gap-1 ${
                                                    page.isVariant ? 'ml-4' : ''
                                                }`}>
                                                    <button
                                                        type="button"
                                                        onClick={() => goToPage(index)}
                                                        className={`flex-1 text-left px-2 py-1.5 rounded-lg text-sm transition-all duration-200 flex items-center gap-1.5 ${
                                                            colorClasses[page.color]
                                                        }`}
                                                    >
                                                        <span className="text-sm">{page.icon}</span>
                                                        <span className="truncate">{page.title}</span>
                                                        {isActive && <span className="ml-auto text-xs">●</span>}
                                                    </button>
                                                    
                                                    {page.isVariant && (
                                                        <button
                                                            type="button"
                                                            onClick={(e) => {
                                                                e.stopPropagation();
                                                                const variantIndex = parseInt(page.id.split('-')[1]);
                                                                handleRemoveVariant(variantIndex);
                                                            }}
                                                            className={`w-5 h-5 rounded-full flex items-center justify-center text-xs font-bold hover:bg-red-100 text-red-500 hover:text-red-600 transition-colors ${
                                                                theme === 'dark' ? 'hover:bg-red-900/20' : ''
                                                            }`}
                                                            title="Eliminar variante"
                                                        >
                                                            ×
                                                        </button>
                                                    )}
                                                </div>
                                            );
                                        })}
                                        
                                        {/* Botón añadir variante */}
                                        <button
                                            type="button"
                                            onClick={handleAddVariant}
                                            className={`w-full text-left px-2 py-1.5 rounded-lg text-sm transition-all duration-200 flex items-center gap-1.5 mt-2 border-t pt-2 ${
                                                theme === 'light' 
                                                    ? 'hover:bg-green-50 text-green-600 hover:text-green-700 hover:shadow-sm border-gray-200' 
                                                    : 'hover:bg-green-900/20 text-green-400 hover:text-green-300 hover:shadow-sm border-gray-600'
                                            }`}
                                        >
                                            <Plus size={12} />
                                            Añadir Variante
                                        </button>
                                    </div>
                                </div>
                            </div>

                            {/* Contenido principal */}
                            <div className="flex-1 relative overflow-hidden">
                                {/* Contenedor de páginas */}
                                <div 
                                    className="flex h-full transition-transform duration-500 ease-in-out"
                                    style={{ transform: `translateX(-${currentPage * 100}%)` }}
                                >
                                    {pages.map((page, index) => (
                                        <div key={page.id} className="w-full flex-shrink-0 overflow-y-auto" style={{
                                            scrollbarWidth: 'thin',
                                            scrollbarColor: '#9ca3af #374151'
                                        }}>
                                            <div className="p-4 h-full">
                                                <div className="space-y-6">
                                                    <div className="flex items-center gap-3 mb-6">
                                                        <div className={`w-10 h-10 rounded-full flex items-center justify-center text-lg ${
                                                            theme === 'light' ? 'bg-blue-100 text-blue-800' : 'bg-blue-900/50 text-blue-200'
                                                        }`}>
                                                            {page.icon}
                                                        </div>
                                                        <div>
                                                            <h2 className={`text-xl font-bold ${
                                                                theme === 'light' ? 'text-text-emphasis' : 'text-gray-100'
                                                            }`}>{page.title}</h2>
                                                            <p className={`text-sm ${
                                                                theme === 'light' ? 'text-text-muted' : 'text-gray-400'
                                                            }`}>Página {index + 1} de {totalPages}</p>
                                                        </div>
                                                    </div>
                                                    
                                                    <div className="text-center py-8">
                                                        <p className={`text-lg ${
                                                            theme === 'light' ? 'text-text-base' : 'text-gray-300'
                                                        }`}>Contenido de {page.title}</p>
                                                        <p className={`text-sm mt-2 ${
                                                            theme === 'light' ? 'text-text-muted' : 'text-gray-400'
                                                        }`}>Esta página está en construcción</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                                
                                {/* Controles de navegación */}
                                <div className="absolute bottom-4 left-1/2 transform -translate-x-1/2 flex items-center gap-3 bg-black/20 backdrop-blur-sm rounded-full px-4 py-2">
                                    <button
                                        type="button"
                                        onClick={prevPage}
                                        disabled={currentPage === 0}
                                        className={`w-8 h-8 rounded-full flex items-center justify-center transition-all duration-200 ${
                                            currentPage === 0 
                                                ? 'bg-gray-400/50 text-gray-600 cursor-not-allowed' 
                                                : 'bg-white/20 hover:bg-white/30 text-white hover:scale-110'
                                        }`}
                                        title="Página anterior (←)"
                                    >
                                        ←
                                    </button>
                                    
                                    <span className="text-white text-sm font-medium px-2">
                                        {currentPage + 1} / {totalPages}
                                    </span>
                                    
                                    <button
                                        type="button"
                                        onClick={nextPage}
                                        disabled={currentPage === totalPages - 1}
                                        className={`w-8 h-8 rounded-full flex items-center justify-center transition-all duration-200 ${
                                            currentPage === totalPages - 1 
                                                ? 'bg-gray-400/50 text-gray-600 cursor-not-allowed' 
                                                : 'bg-white/20 hover:bg-white/30 text-white hover:scale-110'
                                        }`}
                                        title="Página siguiente (→)"
                                    >
                                        →
                                    </button>
                                </div>
                                
                                {/* Botón de envío flotante */}
                                <div className="absolute top-4 right-4 z-10">
                                    <button
                                        type="button"
                                        onClick={onSubmit}
                                        disabled={loading}
                                        className={`px-6 py-3 rounded-xl font-semibold flex items-center gap-2 transition-all duration-300 text-sm shadow-lg hover:shadow-xl transform hover:scale-105 ${
                                            loading 
                                                ? 'bg-gray-400 cursor-not-allowed' 
                                                : 'bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-white'
                                        }`}
                                    >
                                        {loading ? <Loader2 size={14} className="animate-spin" /> : <Save size={14} />}
                                        {isNewProduct ? 'Crear' : 'Actualizar'}
                                    </button>
                                </div>
                            </div>
                        </div>
                    </ErrorBoundary>
                </div>
                
                {/* Modal de confirmación para eliminar variantes */}
                {showVariantDeleteConfirm && (
                    <div className="fixed inset-0 bg-black bg-opacity-60 flex items-center justify-center z-50 p-4">
                        <div className={`rounded-lg shadow-2xl p-6 w-full max-w-md border ${
                            theme === 'light' ? 'bg-surface-primary border-border-subtle' : 'bg-gray-800 border-gray-600'
                        }`}>
                            <div className="flex items-center gap-3 mb-4">
                                <div className="w-10 h-10 rounded-full bg-orange-100 flex items-center justify-center">
                                    <AlertTriangle size={20} className="text-orange-600" />
                                </div>
                                <h3 className={`text-lg font-bold ${
                                    theme === 'light' ? 'text-text-emphasis' : 'text-gray-100'
                                }`}>¿Eliminar Variantes?</h3>
                            </div>
                            
                            <p className={`text-sm mb-6 ${
                                theme === 'light' ? 'text-text-base' : 'text-gray-200'
                            }`}>
                                Tienes <span className="font-bold text-orange-600">{productData.variants?.length} variante(s)</span> con información. 
                                Al cambiar a "Producto Simple" se eliminarán permanentemente.
                            </p>
                            
                            <div className="flex gap-3 justify-end">
                                <button
                                    onClick={() => setShowVariantDeleteConfirm(false)}
                                    className={`px-4 py-2 rounded-lg font-medium transition-colors ${
                                        theme === 'light' 
                                            ? 'bg-gray-100 hover:bg-gray-200 text-gray-700' 
                                            : 'bg-gray-600 hover:bg-gray-500 text-gray-200'
                                    }`}
                                >
                                    Cancelar
                                </button>
                                <button
                                    onClick={confirmDeleteVariants}
                                    className="px-4 py-2 rounded-lg font-medium bg-red-600 hover:bg-red-700 text-white transition-colors flex items-center gap-2"
                                >
                                    <AlertTriangle size={16} />
                                    Sí, Eliminar
                                </button>
                            </div>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};

export default AddEditProductForm;




                                    {/* Sección de Precios */}
                                    <section 
                                        ref={el => sectionRefs.current['pricing'] = el}
                                        data-section="pricing"
                                        className="space-y-4"
                                    >
                                        <div className="flex items-center gap-2 mb-3">
                                            <div className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold ${
                                                theme === 'light' ? 'bg-green-100 text-green-800' : 'bg-green-900/50 text-green-200'
                                            }`}>
                                                💰
                                            </div>
                                            <h3 className={`text-lg font-bold ${
                                                theme === 'light' ? 'text-text-emphasis' : 'text-gray-100'
                                            }`}>Costo y Precio</h3>
                                        </div>

                                        <div className="flex gap-4">
                                            {/* Columna principal con campos */}
                                            <div className="flex-1">
                                                {/* Fila 1: Costo + Moneda + Stock */}
                                                <div className="grid grid-cols-1 md:grid-cols-12 gap-4 mb-4">
                                                    {/* Costo Unitario */}
                                                    <div className="md:col-span-5">
                                                        <label className={`block text-sm font-medium mb-2 ${
                                                            theme === 'light' ? 'text-text-base' : 'text-gray-200'
                                                        }`}>
                                                            Costo Unitario *
                                                        </label>
                                                        <input
                                                            type="number"
                                                            name="costPrice"
                                                            value={productData.costPrice || ''}
                                                            onChange={handleProductInputChange}
                                                            step="0.01"
                                                            className={`w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 ${
                                                                formErrors.costPrice ? 'border-red-500' : 
                                                                theme === 'light' ? 'border-border-subtle bg-white text-text-base' : 'border-gray-600 bg-gray-700 text-gray-100'
                                                            }`}
                                                            placeholder="15.00"
                                                            required={!productData.variants || productData.variants.length === 0}
                                                            disabled={productData.variants && productData.variants.length > 0}
                                                        />
                                                        {formErrors.costPrice && <p className="text-red-500 text-xs mt-1">{formErrors.costPrice}</p>}
                                                    </div>

                                                    {/* Selector de Moneda */}
                                                    <div className="md:col-span-2">
                                                        <label className={`block text-sm font-medium mb-2 ${
                                                            theme === 'light' ? 'text-text-base' : 'text-gray-200'
                                                        }`}>
                                                            Moneda
                                                        </label>
                                                        <select
                                                            name="costCurrency"
                                                            value={productData.costCurrency || 'USD'}
                                                            onChange={handleProductInputChange}
                                                            className={`w-center px-1 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 ${
                                                                theme === 'light' ? 'border-border-subtle bg-white text-text-base' : 'border-gray-600 bg-gray-700 text-gray-100'
                                                            }`}
                                                            disabled={productData.variants && productData.variants.length > 0}
                                                        >
                                                            {currencies.map(currency => (
                                                                <option key={currency} value={currency}>{currency}</option>
                                                            ))}
                                                        </select>
                                                    </div>

                                                    {/* Stock */}
                                                    <div className="md:col-span-5">
                                                        <label className={`block text-sm font-medium mb-2 ${
                                                            theme === 'light' ? 'text-text-base' : 'text-gray-200'
                                                        }`}>
                                                            Stock *
                                                        </label>
                                                        <input
                                                            type="number"
                                                            name="stock"
                                                            value={productData.stock || ''}
                                                            onChange={handleProductInputChange}
                                                            className={`w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 ${
                                                                formErrors.stock ? 'border-red-500' : 
                                                                theme === 'light' ? 'border-border-subtle bg-white text-text-base' : 'border-gray-600 bg-gray-700 text-gray-100'
                                                            }`}
                                                            placeholder="100"
                                                            required={!productData.variants || productData.variants.length === 0}
                                                            disabled={productData.variants && productData.variants.length > 0}
                                                        />
                                                        {formErrors.stock && <p className="text-red-500 text-xs mt-1">{formErrors.stock}</p>}
                                                        {/* Total de inversión */}
                                                        {productData.costPrice && productData.stock && (
                                                            <div className={`mt-2 px-3 py-2 rounded-lg text-sm ${
                                                                theme === 'light' ? 'bg-orange-50 text-orange-700 border border-orange-200' : 'bg-orange-900/30 text-orange-300 border border-orange-700'
                                                            }`}>
                                                                📊 Total Inversión: {productData.costCurrency || 'USD'} {(Number(productData.costPrice) * Number(productData.stock)).toFixed(2)}
                                                            </div>
                                                        )}
                                                    </div>
                                                </div>

                                                {/* Fila 2: Unidad + % Ganancia + Precio */}
                                                <div className="grid grid-cols-1 md:grid-cols-12 gap-4">
                                                    {/* Unidad de Medida */}
                                                    <div className="md:col-span-4">
                                                        <label className={`block text-sm font-medium mb-2 ${
                                                            theme === 'light' ? 'text-text-base' : 'text-gray-200'
                                                        }`}>
                                                            Unidad *
                                                        </label>
                                                        <select
                                                            name="unitOfMeasure"
                                                            value={productData.unitOfMeasure || 'unidad'}
                                                            onChange={handleProductInputChange}
                                                            className={`w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 ${
                                                                formErrors.unitOfMeasure ? 'border-red-500' : 
                                                                theme === 'light' ? 'border-border-subtle bg-white text-text-base' : 'border-gray-600 bg-gray-700 text-gray-100'
                                                            }`}
                                                            required={!productData.variants || productData.variants.length === 0}
                                                            disabled={productData.variants && productData.variants.length > 0}
                                                        >
                                                            {unitOfMeasureOptions.map(unit => (
                                                                <option key={unit} value={unit}>{unit}</option>
                                                            ))}
                                                        </select>
                                                        {formErrors.unitOfMeasure && <p className="text-red-500 text-xs mt-1">{formErrors.unitOfMeasure}</p>}
                                                    </div>

                                                    {/* % Ganancia */}
                                                    <div className="md:col-span-2">
                                                        <label className={`block text-sm font-medium mb-2 ${
                                                            theme === 'light' ? 'text-text-base' : 'text-gray-200'
                                                        }`}>
                                                            %
                                                        </label>
                                                        <input
                                                            type="number"
                                                            name="profitPercentage"
                                                            value={productData.profitPercentage || ''}
                                                            onChange={handleProductInputChange}
                                                            step="0.1"
                                                            min="0"
                                                            max="999"
                                                            className={`w-full px-2 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-center ${
                                                                formErrors.profitPercentage ? 'border-red-500' : 
                                                                theme === 'light' ? 'border-border-subtle bg-white text-text-base' : 'border-gray-600 bg-gray-700 text-gray-100'
                                                            }`}
                                                            placeholder="30"
                                                            disabled={productData.variants && productData.variants.length > 0}
                                                        />
                                                        {formErrors.profitPercentage && <p className="text-red-500 text-xs mt-1">{formErrors.profitPercentage}</p>}
                                                        {calculatedProductProfitPercentage !== null && (
                                                            <p className={`text-xs mt-1 text-center ${
                                                                theme === 'light' ? 'text-blue-600' : 'text-blue-400'
                                                            }`}>
                                                                {parseFloat(calculatedProductProfitPercentage).toFixed(1)}%
                                                            </p>
                                                        )}
                                                    </div>

                                                    {/* Precio de Venta */}
                                                    <div className="md:col-span-6">
                                                        <label className={`block text-sm font-medium mb-2 ${
                                                            theme === 'light' ? 'text-text-base' : 'text-gray-200'
                                                        }`}>
                                                            Precio de Venta
                                                            <span className={`text-xs ml-1 ${
                                                                theme === 'light' ? 'text-blue-600' : 'text-blue-400'
                                                            }`}>(Auto)</span>
                                                        </label>
                                                        <div className="flex gap-1">
                                                            <div className="relative flex-1">
                                                                <input
                                                                    type="number"
                                                                    value={calculatedProductPricePlaceholder !== null ? parseFloat(calculatedProductPricePlaceholder).toFixed(2) : ''}
                                                                    readOnly
                                                                    className={`w-full px-3 py-2 border rounded-lg ${
                                                                        theme === 'light' ? 'border-border-subtle bg-gray-50 text-text-base' : 'border-gray-600 bg-gray-600 text-gray-100'
                                                                    }`}
                                                                    disabled={productData.variants && productData.variants.length > 0}
                                                                    placeholder="Calculado"
                                                                />
                                                                {calculatedProductPricePlaceholder !== null && (
                                                                    <div className={`absolute right-8 top-2 text-xs ${
                                                                        theme === 'light' ? 'text-green-600' : 'text-green-400'
                                                                    }`}>
                                                                        🔄
                                                                    </div>
                                                                )}
                                                            </div>
                                                            <select
                                                                name="saleCurrency"
                                                                value={productData.saleCurrency || 'USD'}
                                                                onChange={handleProductInputChange}
                                                                className={`w-16 px-1 py-2 border rounded-lg text-xs ${
                                                                    theme === 'light' ? 'border-border-subtle bg-white text-text-base' : 'border-gray-600 bg-gray-700 text-gray-100'
                                                                }`}
                                                                disabled={productData.variants && productData.variants.length > 0}
                                                            >
                                                                {currencies.map(currency => (
                                                                    <option key={currency} value={currency}>{currency}</option>
                                                                ))}
                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            {/* Sidebar: Ganancia Neta (siempre visible) */}
                                            <div className={`w-64 p-3 rounded-lg border ${
                                                theme === 'light' ? 'bg-green-50 border-green-200' : 'bg-green-900/20 border-green-700'
                                            }`}>
                                                <h4 className={`text-lg font-bold mb-2 text-center ${
                                                    theme === 'light' ? 'text-green-800' : 'text-green-300'
                                                }`}>
                                                    Ganancia Neta
                                                </h4>
                                                
                                                {(() => {
                                                    const costo = Number(productData.costPrice) || 0;
                                                    const stock = Number(productData.stock) || 0;
                                                    const precio = calculatedProductPricePlaceholder ? Number(calculatedProductPricePlaceholder) : 0;
                                                    
                                                    const totalVenta = precio * stock;
                                                    const totalCosto = costo * stock;
                                                    const gananciaNeta = totalVenta - totalCosto;
                                                    
                                                    const hasData = costo > 0 && stock > 0 && precio > 0;
                                                    
                                                    return (
                                                        <div className="space-y-2 text-sm">
                                                            <div className={`text-center text-2xl font-bold mb-3 ${
                                                                hasData 
                                                                    ? theme === 'light' ? 'text-green-700' : 'text-green-200'
                                                                    : theme === 'light' ? 'text-gray-400' : 'text-gray-500'
                                                            }`}>
                                                                {hasData 
                                                                    ? `${productData.saleCurrency || 'USD'} ${gananciaNeta.toFixed(2)}`
                                                                    : '-- --'
                                                                }
                                                            </div>
                                                            
                                                            <div className={`p-2 rounded border-l-4 ${
                                                                theme === 'light' ? 'bg-blue-50 border-blue-400 text-blue-700' : 'bg-blue-900/30 border-blue-500 text-blue-300'
                                                            }`}>
                                                                <div className="flex justify-between">
                                                                    <span>📈 Total Venta:</span>
                                                                    <span className="font-semibold">
                                                                        {hasData 
                                                                            ? `${productData.saleCurrency || 'USD'} ${totalVenta.toFixed(2)}`
                                                                            : '--'
                                                                        }
                                                                    </span>
                                                                </div>
                                                            </div>
                                                            
                                                            <div className={`p-2 rounded border-l-4 ${
                                                                theme === 'light' ? 'bg-orange-50 border-orange-400 text-orange-700' : 'bg-orange-900/30 border-orange-500 text-orange-300'
                                                            }`}>
                                                                <div className="flex justify-between">
                                                                    <span>💰 Total Costo:</span>
                                                                    <span className="font-semibold">
                                                                        {hasData 
                                                                            ? `${productData.costCurrency || 'USD'} ${totalCosto.toFixed(2)}`
                                                                            : '--'
                                                                        }
                                                                    </span>
                                                                </div>
                                                            </div>
                                                            
                                                            <div className={`p-2 rounded border-l-4 ${
                                                                theme === 'light' ? 'bg-green-50 border-green-400 text-green-700' : 'bg-green-900/30 border-green-500 text-green-300'
                                                            }`}>
                                                                <div className="flex justify-between">
                                                                    <span>🎯 Ganancia:</span>
                                                                    <span className="font-bold">
                                                                        {hasData 
                                                                            ? `${productData.saleCurrency || 'USD'} ${gananciaNeta.toFixed(2)}`
                                                                            : '--'
                                                                        }
                                                                    </span>
                                                                </div>
                                                            </div>
                                                            
                                                            <div className={`text-center text-xs mt-3 ${
                                                                theme === 'light' ? 'text-green-600' : 'text-green-400'
                                                            }`}>
                                                                {hasData && totalVenta > 0
                                                                    ? `Margen: ${((gananciaNeta / totalVenta) * 100).toFixed(1)}%`
                                                                    : 'Ingresa costo y stock'
                                                                }
                                                            </div>
                                                        </div>
                                                    );
                                                })()
                                                }
                                            </div>
                                        </div>
                                    </section>

                                    {/* Sección Avanzada */}
                                    <section 
                                        ref={el => sectionRefs.current['advanced'] = el}
                                        data-section="advanced"
                                        className="space-y-4"
                                    >
                                        <div className="flex items-center gap-2 mb-3">
                                            <div className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold ${
                                                theme === 'light' ? 'bg-gray-100 text-gray-800' : 'bg-gray-600 text-gray-200'
                                            }`}>
                                                ⚙️
                                            </div>
                                            <h3 className={`text-lg font-bold ${
                                                theme === 'light' ? 'text-text-emphasis' : 'text-gray-100'
                                            }`}>Opciones Avanzadas</h3>
                                        </div>

                                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                            {/* Proveedor */}
                                            <div>
                                                <label className={`block text-sm font-medium mb-2 ${
                                                    theme === 'light' ? 'text-text-base' : 'text-gray-200'
                                                }`}>Proveedor</label>
                                                <input
                                                    type="text"
                                                    name="supplier"
                                                    value={productData.supplier || ''}
                                                    onChange={handleProductInputChange}
                                                    className={`w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 ${
                                                        theme === 'light' ? 'border-border-subtle bg-white text-text-base' : 'border-gray-600 bg-gray-700 text-gray-100'
                                                    }`}
                                                    placeholder="Ej. Distribuciones ABC"
                                                />
                                            </div>

                                            {/* URL de Imagen */}
                                            <div>
                                                <label className={`block text-sm font-medium mb-2 ${
                                                    theme === 'light' ? 'text-text-base' : 'text-gray-200'
                                                }`}>
                                                    URL de Imagen
                                                </label>
                                                <input
                                                    type="url"
                                                    name="imageUrl"
                                                    value={productData.imageUrl || ''}
                                                    onChange={handleProductInputChange}
                                                    onBlur={handleMainImageUrlBlur}
                                                    className={`w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 ${
                                                        formErrors.imageUrl ? 'border-red-500' : 
                                                        theme === 'light' ? 'border-border-subtle bg-white text-text-base' : 'border-gray-600 bg-gray-700 text-gray-100'
                                                    }`}
                                                    placeholder="https://ejemplo.com/imagen.jpg"
                                                />
                                                {formErrors.imageUrl && <p className="text-red-500 text-xs mt-1">{formErrors.imageUrl}</p>}
                                            </div>

                                            {/* Color (solo para productos simples) */}
                                            <div>
                                                <label className={`block text-sm font-medium mb-2 ${
                                                    theme === 'light' ? 'text-text-base' : 'text-gray-200'
                                                }`}>
                                                    Color
                                                </label>
                                                <input
                                                    type="text"
                                                    name="color"
                                                    value={productData.color || ''}
                                                    onChange={handleProductInputChange}
                                                    className={`w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 ${
                                                        theme === 'light' ? 'border-border-subtle bg-white text-text-base' : 'border-gray-600 bg-gray-700 text-gray-100'
                                                    }`}
                                                    placeholder="Ej. Azul, Negro"
                                                    disabled={productData.variants && productData.variants.length > 0}
                                                />
                                            </div>

                                            {/* Talla/Tamaño (solo para productos simples) */}
                                            <div>
                                                <label className={`block text-sm font-medium mb-2 ${
                                                    theme === 'light' ? 'text-text-base' : 'text-gray-200'
                                                }`}>
                                                    Talla/Tamaño
                                                </label>
                                                <input
                                                    type="text"
                                                    name="size"
                                                    value={productData.size || ''}
                                                    onChange={handleProductInputChange}
                                                    className={`w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 ${
                                                        theme === 'light' ? 'border-border-subtle bg-white text-text-base' : 'border-gray-600 bg-gray-700 text-gray-100'
                                                    }`}
                                                    placeholder="Ej. S, L, XL"
                                                    disabled={productData.variants && productData.variants.length > 0}
                                                />
                                            </div>

                                            {/* Material (solo para productos simples) */}
                                            <div>
                                                <label className={`block text-sm font-medium mb-2 ${
                                                    theme === 'light' ? 'text-text-base' : 'text-gray-200'
                                                }`}>
                                                    Material
                                                </label>
                                                <input
                                                    type="text"
                                                    name="material"
                                                    value={productData.material || ''}
                                                    onChange={handleProductInputChange}
                                                    className={`w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 ${
                                                        theme === 'light' ? 'border-border-subtle bg-white text-text-base' : 'border-gray-600 bg-gray-700 text-gray-100'
                                                    }`}
                                                    placeholder="Ej. Algodón, Plástico"
                                                    disabled={productData.variants && productData.variants.length > 0}
                                                />
                                            </div>
                                        </div>

                                        {/* Gestión de Stock Avanzada */}
                                        <div className={`p-4 rounded-lg border ${
                                            theme === 'light' ? 'border-border-subtle bg-surface-secondary' : 'border-gray-600 bg-gray-700'
                                        }`}>
                                            <h4 className={`text-lg font-semibold mb-4 ${
                                                theme === 'light' ? 'text-text-emphasis' : 'text-gray-100'
                                            }`}>Gestión de Stock</h4>
                                            
                                            <div className="space-y-4">
                                                <label className="flex items-center">
                                                    <input
                                                        type="checkbox"
                                                        name="isPerishable"
                                                        checked={productData.isPerishable || false}
                                                        onChange={handleProductInputChange}
                                                        className="mr-2 text-blue-600"
                                                        disabled={productData.variants && productData.variants.length > 0}
                                                    />
                                                    <span className={theme === 'light' ? 'text-text-base' : 'text-gray-200'}>
                                                        ¿Es Perecedero?
                                                    </span>
                                                </label>

                                                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                                    <div>
                                                        <label className={`block text-sm font-medium mb-2 ${
                                                            theme === 'light' ? 'text-text-base' : 'text-gray-200'
                                                        }`}>
                                                            Umbral de Reaprovisionamiento
                                                        </label>
                                                        <input
                                                            type="number"
                                                            name="reorderThreshold"
                                                            value={productData.reorderThreshold || ''}
                                                            onChange={handleProductInputChange}
                                                            className={`w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 ${
                                                                theme === 'light' ? 'border-border-subtle bg-white text-text-base' : 'border-gray-600 bg-gray-700 text-gray-100'
                                                            }`}
                                                            placeholder="10"
                                                            disabled={productData.variants && productData.variants.length > 0}
                                                        />
                                                    </div>

                                                    {productData.isPerishable && (
                                                        <>
                                                            <div>
                                                                <label className={`block text-sm font-medium mb-2 ${
                                                                    theme === 'light' ? 'text-text-base' : 'text-gray-200'
                                                                }`}>
                                                                    Stock Óptimo Máximo
                                                                </label>
                                                                <input
                                                                    type="number"
                                                                    name="optimalMaxStock"
                                                                    value={productData.optimalMaxStock || ''}
                                                                    onChange={handleProductInputChange}
                                                                    className={`w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 ${
                                                                        theme === 'light' ? 'border-border-subtle bg-white text-text-base' : 'border-gray-600 bg-gray-700 text-gray-100'
                                                                    }`}
                                                                    placeholder="50"
                                                                    disabled={productData.variants && productData.variants.length > 0}
                                                                />
                                                            </div>
                                                            <div>
                                                                <label className={`block text-sm font-medium mb-2 ${
                                                                    theme === 'light' ? 'text-text-base' : 'text-gray-200'
                                                                }`}>
                                                                    Vida Útil (días)
                                                                </label>
                                                                <input
                                                                    type="number"
                                                                    name="shelfLifeDays"
                                                                    value={productData.shelfLifeDays || ''}
                                                                    onChange={handleProductInputChange}
                                                                    className={`w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 ${
                                                                        theme === 'light' ? 'border-border-subtle bg-white text-text-base' : 'border-gray-600 bg-gray-700 text-gray-100'
                                                                    }`}
                                                                    placeholder="30"
                                                                    disabled={productData.variants && productData.variants.length > 0}
                                                                />
                                                            </div>
                                                        </>
                                                    )}
                                                </div>
                                            </div>
                                        </div>
                                        
                                        {/* Gestión de Imagen Principal */}
                                        <div className={`p-4 rounded-lg border ${
                                            theme === 'light' ? 'border-border-subtle bg-surface-secondary' : 'border-gray-600 bg-gray-700'
                                        }`}>
                                            <h4 className={`text-lg font-semibold mb-4 ${
                                                theme === 'light' ? 'text-text-emphasis' : 'text-gray-100'
                                            }`}>🖼️ Imagen Principal</h4>
                                            
                                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                                {/* Subir archivo */}
                                                <div>
                                                    <label htmlFor="main-image-upload-advanced" className={`w-full py-3 px-4 rounded-lg text-center cursor-pointer transition-colors font-medium flex items-center justify-center gap-2 ${
                                                        theme === 'light' 
                                                            ? 'bg-blue-600 hover:bg-blue-700 text-white' 
                                                            : 'bg-blue-500 hover:bg-blue-600 text-white'
                                                    }`}>
                                                        {isUploadingMainImage ? <Loader2 size={18} className="animate-spin" /> : <Upload size={18} />}
                                                        {isUploadingMainImage ? 'Subiendo...' : 'Subir desde Dispositivo'}
                                                    </label>
                                                    <input
                                                        id="main-image-upload-advanced"
                                                        type="file"
                                                        accept="image/jpeg,image/jpg,image/png,image/gif,image/webp"
                                                        onChange={handleMainImageFileChange}
                                                        className="hidden"
                                                    />
                                                </div>
                                                
                                                {/* Preview mejorado */}
                                                <div>
                                                    {imagePreviewUrl || productData.imageUrl ? (
                                                        <div className={`p-3 rounded-lg border text-center relative ${
                                                            theme === 'light' ? 'border-border-subtle bg-surface-primary' : 'border-gray-600 bg-gray-800'
                                                        }`}>
                                                            <p className={`text-xs mb-2 ${
                                                                theme === 'light' ? 'text-text-muted' : 'text-gray-400'
                                                            }`}>Imagen actual:</p>
                                                            <img
                                                                src={imagePreviewUrl || productData.imageUrl}
                                                                alt="Imagen del producto"
                                                                className="max-w-full h-auto max-h-32 object-contain mx-auto rounded"
                                                                onError={(e) => {
                                                                    e.target.onerror = null;
                                                                    e.target.src = 'https://placehold.co/200x150/gray/white?text=Error+al+cargar';
                                                                }}
                                                            />
                                                            <button
                                                                type="button"
                                                                onClick={handleRemoveMainImage}
                                                                className="absolute top-1 right-1 w-6 h-6 bg-red-500 hover:bg-red-600 text-white rounded-full flex items-center justify-center text-xs font-bold transition-colors shadow-lg"
                                                                title="Eliminar imagen"
                                                            >
                                                                ×
                                                            </button>
                                                        </div>
                                                    ) : (
                                                        <div className={`p-3 rounded-lg border text-center ${
                                                            theme === 'light' ? 'border-border-subtle bg-gray-50' : 'border-gray-600 bg-gray-800'
                                                        }`}>
                                                            <p className={`text-sm ${
                                                                theme === 'light' ? 'text-text-muted' : 'text-gray-400'
                                                            }`}>Sin imagen</p>
                                                        </div>
                                                    )}
                                                </div>
                                            </div>
                                        </div>
                                    </section>

                                    {/* Sección de Variantes */}
                                    {productData.variants && productData.variants.length > 0 && (
                                        <section 
                                            ref={el => sectionRefs.current['variants'] = el}
                                            data-section="variants"
                                            className="space-y-4"
                                        >
                                            <div className="flex items-center gap-2 mb-3">
                                                <div className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold ${
                                                    theme === 'light' ? 'bg-purple-100 text-purple-800' : 'bg-purple-900/50 text-purple-200'
                                                }`}>
                                                    🎨
                                                </div>
                                                <h3 className={`text-lg font-bold ${
                                                    theme === 'light' ? 'text-text-emphasis' : 'text-gray-100'
                                                }`}>Variantes del Producto</h3>
                                            </div>
                                            <div className="space-y-4">
                                                {productData.variants.map((variant, index) => (
                                                    <div 
                                                        key={index} 
                                                        ref={el => sectionRefs.current[`variant-${index}`] = el}
                                                        data-section={`variant-${index}`}
                                                    >
                                                        <VariantForm
                                                            variant={variant}
                                                            index={index}
                                                            handleVariantInputChange={handleVariantInputChange}
                                                            handleRemoveVariant={handleRemoveVariant}
                                                            handleVariantImageFileChange={handleVariantImageFileChange}
                                                            variantImageUploading={variantImageUploading}
                                                            formErrors={formErrors}
                                                            calculatedVariantProfitPercentage={calculatedVariantProfitPercentage[index]}
                                                            calculatedVariantPricePlaceholder={calculatedVariantPricePlaceholder[index]}
                                                            formatPrice={formatPrice}
                                                            availableCurrencies={availableCurrencies}
                                                            unitOfMeasureOptions={unitOfMeasureOptions}
                                                            isExpanded={expandedVariants.has(index)}
                                                            onToggleExpand={() => toggleVariantExpansion(index)}
                                                        />
                                                    </div>
                                                ))}
                                            </div>
                                        </section>
                                    )}

                                    {/* Botón de envío */}
                                    <div className="flex justify-end pt-4 border-t border-gray-200 -mx-3 px-3 bg-opacity-50">
                                        <button
                                            type="submit"
                                            disabled={loading}
                                            className={`px-6 py-3 rounded-xl font-semibold flex items-center gap-2 transition-all duration-300 text-sm shadow-lg hover:shadow-xl transform hover:scale-105 ${
                                                loading 
                                                    ? 'bg-gray-400 cursor-not-allowed' 
                                                    : 'bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-white'
                                            }`}
                                        >
                                            {loading ? <Loader2 size={14} className="animate-spin" /> : <Save size={14} />}
                                            {isNewProduct ? 'Crear Producto' : 'Actualizar Producto'}
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </ErrorBoundary>
                </div>
                
                {/* Modal de confirmación para eliminar variantes */}
                {showVariantDeleteConfirm && (
                    <div className="fixed inset-0 bg-black bg-opacity-60 flex items-center justify-center z-50 p-4">
                        <div className={`rounded-lg shadow-2xl p-6 w-full max-w-md border ${
                            theme === 'light' ? 'bg-surface-primary border-border-subtle' : 'bg-gray-800 border-gray-600'
                        }`}>
                            <div className="flex items-center gap-3 mb-4">
                                <div className="w-10 h-10 rounded-full bg-orange-100 flex items-center justify-center">
                                    <AlertTriangle size={20} className="text-orange-600" />
                                </div>
                                <h3 className={`text-lg font-bold ${
                                    theme === 'light' ? 'text-text-emphasis' : 'text-gray-100'
                                }`}>¿Eliminar Variantes?</h3>
                            </div>
                            
                            <p className={`text-sm mb-6 ${
                                theme === 'light' ? 'text-text-base' : 'text-gray-200'
                            }`}>
                                Tienes <span className="font-bold text-orange-600">{productData.variants?.length} variante(s)</span> con información. 
                                Al cambiar a "Producto Simple" se eliminarán permanentemente.
                            </p>
                            
                            <div className="flex gap-3 justify-end">
                                <button
                                    onClick={() => setShowVariantDeleteConfirm(false)}
                                    className={`px-4 py-2 rounded-lg font-medium transition-colors ${
                                        theme === 'light' 
                                            ? 'bg-gray-100 hover:bg-gray-200 text-gray-700' 
                                            : 'bg-gray-600 hover:bg-gray-500 text-gray-200'
                                    }`}
                                >
                                    Cancelar
                                </button>
                                <button
                                    onClick={confirmDeleteVariants}
                                    className="px-4 py-2 rounded-lg font-medium bg-red-600 hover:bg-red-700 text-white transition-colors flex items-center gap-2"
                                >
                                    <AlertTriangle size={16} />
                                    Sí, Eliminar
                                </button>
                            </div>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};

export default AddEditProductForm;